# Generated by Django 4.2.7 on 2023-11-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoCrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
